# Lab 1

This is my first lab

In [5]:
import pandas as pd

covid_data = pd.read_csv("s3://kdr-ia-340-2025/data.csv")
covid_data.head()

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
0,14/12/2020,14,12,2020,746,6,Afghanistan,AF,AFG,38041757.0,Asia,9.013779
1,13/12/2020,13,12,2020,298,9,Afghanistan,AF,AFG,38041757.0,Asia,7.052776
2,12/12/2020,12,12,2020,113,11,Afghanistan,AF,AFG,38041757.0,Asia,6.868768
3,11/12/2020,11,12,2020,63,10,Afghanistan,AF,AFG,38041757.0,Asia,7.134266
4,10/12/2020,10,12,2020,202,16,Afghanistan,AF,AFG,38041757.0,Asia,6.968658

In [6]:
lottery_data = pd.read_csv("s3://kdr-ia-340-2025/Lottery_Powerball_Winning_Numbers__Beginning_2010.csv")
lottery_data.head()

    Draw Date    Winning Numbers  Multiplier
0  09/26/2020  11 21 27 36 62 24         3.0
1  09/30/2020  14 18 36 49 67 18         2.0
2  10/03/2020  18 31 36 43 47 20         2.0
3  10/07/2020  06 24 30 53 56 19         2.0
4  10/10/2020  05 18 23 40 50 18         3.0